language: generic
env:
  - EMACS=emacs-snapshot

branches:
  only:
    - master
    - develop

before_install:
  sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
  sudo apt-get -qq update &&
  sudo apt-get -qq -f install &&
  sudo apt-get -qqy install emacs-snapshot;

install:
  - source test/travis-ci.sh
  - '"$EMACS" --version'

script:
  - byte-compile
